CREATE TABLE dog_date_dogs_in_howls (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    howl_id INT REFERENCES dog_date_howls(id) ON DELETE CASCADE NOT NULL,
    dog_id INT REFERENCES dog_date_dog_profiles(id) ON DELETE CASCADE NOT NULL
);