CREATE TABLE dog_date_time_windows (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    howl_id INT REFERENCES dog_date_howls(id) ON DELETE CASCADE NOT NULL,
    day_of_week TEXT,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL
);