CREATE TABLE dog_date_user_saved_howls (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT REFERENCES dog_date_users(id) ON DELETE CASCADE NOT NULL,
    howl_id INT REFERENCES dog_date_howls(id) ON DELETE CASCADE NOT NULL
);